apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - stirling-pdf-certificate.yaml
  - stirling-pdf-repo.yaml
  - stirling-pdf-ingressroute.yaml
  - stirling-pdf-helmrelease.yaml
