apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - immich-certificate.yaml
  - immich-storage.yaml
  - immich-db.yaml
  - immich-redis.yaml
  - immich-aliases.yaml
  - immich-ingressroute.yaml
  - immich-repo.yaml
  - immich-helmrelease.yaml
