apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./install.yaml
  - grafana-certificate.yaml
  - grafana-admin-secret.yaml
  - prometheus-repo.yaml
  - unpoller-secret.yaml
  - unpoller-repo.yaml
  - prometheus-stack-helmrelease.yaml
  - unpoller-helmrelease.yaml
