# monitoring/prometheus-stack-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "81.6.3"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 5m
  values:
    # --- Grafana Configuration ---
    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: "admin-user"
        passwordKey: "admin-password"

      persistence:
        enabled: true
        type: pvc
        size: 20Gi
        storageClassName: "longhorn"

      service:
        type: ClusterIP

    # --- Prometheus Configuration ---
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "longhorn"
              resources:
                requests:
                  storage: 40Gi

        secrets:
          - home-assistant-token

        volumeMounts:
          - name: secret-home-assistant-token
            mountPath: /etc/prometheus/secrets/ha-token
            readOnly: true

        additionalScrapeConfigs: |
          - job_name: "home-assistant"
            metrics_path: /api/prometheus
            bearer_token_file: /etc/prometheus/secrets/ha-token/token
            scheme: https
            static_configs:
              - targets: ["ha.seanzhong.com"]
